---
sidebar: sidebar 
permalink: concept_get_started_with_health_check_dashboard.html 
keywords: activeiq, health check, health, hca, health check dashboard, autosupport, autosupport adoption, recommended configuration, best practices, support, support and entitlements, support contract, contracts, active contracts, expired contracts, nearing-expiration, key recommendations, recommendations, digital advisor, features, recommended software 
summary: 提供儀表板、健全狀況分數、功能和小工具的相關資訊。 
---
= 開始使用Digital Advisor健康檢查儀表板
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
此儀表板可透過下列小工具、提供已安裝基礎的概覽摘要：

* *AutoSupport 採用率*：顯示已啟用 AutoSupport 的系統數量和百分比。您也可以檢視標記為「已拒絕」的系統、已啟用 *HTTPS* 和 *AutoSupport on Demand* 的系統，以及 *訊號遺失* 的系統（指過去 7 天內停止傳送 AutoSupport 資料的系統）。若要檢視您的資訊健檢評分及安裝基礎中系統的相關資訊，請選取 *AutoSupport 採用率* 小工具。
* *建議組態*：根據*建議組態*小工具、顯示相容且不相容的系統。這有助於您採取行動、確保系統在安裝基礎上均設定完善。您可以檢視儀表板上提供的分數、並根據依優先順序提供的重要建議採取行動。
* *推薦軟體*：顯示所有軟體與韌體升級及貨幣建議的合併清單。您可以檢視AutoSupport 啟用了支援功能的系統、這些系統應為最低或最新的軟體或韌體版本。
* *支援與權益*：顯示已過期和即將到期（6 至 12 個月內）的支援合約。它會顯示已停止支援的平台、磁碟、機架、權益法規遵循、即將到期的項目，以及平台和硬體的支援終止不適用情況。您可以在儀表板檢視資訊健檢評分，並根據按優先順序排序的關鍵建議採取相應措施。若要檢視支援合約的詳細資訊，請選擇 *支援與權益* 小工具。您也可以使用此小工具續約支援合約。
* *最佳實務做法*：透過評估儲存系統的最佳實務做法屬性來顯示健全狀況檢查分數、包括效能與效率、可用度與保護、容量、組態及安全性弱點。NetApp最佳實務做法有助於維持系統健全狀況、使安裝基礎的效能最佳化。
* *技術案例*：根據案例類型、開啟或關閉狀態、以及可選擇的時間範圍、提供您技術案例歷程的詳細檢視。  您可以深入案例群組、並透過檢視案例詳細資料 link:https://mysupport.netapp.com//["NetApp 支援網站"^] 或其他案例入口網站。

