---
sidebar: sidebar 
permalink: concept_understand_activeiq_features.html 
keywords: activeiq, active iq digital advisor, features, upgrade, support offering 
summary: 提供儀表板、觀察清單、功能和小工具的相關資訊。 
---
= 瞭Active IQ 解功能
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
您可以在觀察清單層級，使用 Active IQ Digital Advisor 來檢視儲存系統整體狀態、系統健全度高階資訊、庫存容量、規劃升級、升級選項、及寶貴洞見。

第一次存取 Active IQ Digital Advisor 時，您可以建立一份觀察清單，或是直接搜尋客戶名稱、網站名稱、群組名稱、StorageGRID、主機名稱、叢集、序號或系統 ID。

您也應該瞭解套用至卡片的色彩、這些色彩會指出風險的嚴重性和類型。

以下是 Active IQ Digital Advisor 的一些功能：

* 檢視多份報價表、可據以行動且實用的資訊一覽表
* 深入瞭解儲存系統的所有風險、以及降低風險的行動
* 利用本解決方法降低風險Active IQ Unified Manager
* 升級您的儲存系統
* 檢視儲存效率比、使用的邏輯空間、使用的實體空間、以及執行ONTAP 更新版本的儲存系統所儲存的總資料
* 檢視效能資料的圖形格式、以分析儲存設備的效能
* 取得未來6個月內已過期或即將到期的硬體與軟體相關資訊
* 使用Ansible更新ONTAP 您的韌體
* 取得超過90%容量或接近90%容量的系統詳細資料
* 檢視詳細的實體和邏輯組態資訊、包括叢集和節點組態摘要、本機層級和磁碟區資訊、網路介面和連接埠資訊、詳細說明磁碟和磁碟櫃資訊的堆疊圖表、以及幾種纜線視覺效果
* 提供跨堆疊的資訊與洞見、有助於疑難排解、升級評估、解決方案驗證及移轉
* 檢查主機的相容性、並針對主機作業系統、驅動程式和韌體提供升級建議
* 以更聰明、更快速的方式、準確找到您想要的產品



NOTE: 您可以從系統儀表板上的*組態*小工具升級支援服務、以深入瞭解您的安裝基礎、並獲得個人化支援。
