---
sidebar: sidebar 
permalink: digital-advisor-integration-with-console.html 
keywords: digital advisor, integration, netapp console 
summary: 'Digital Advisor現已與NetApp Console 完全整合。現在您可以從NetApp控制台使用者介面 (UI) 管理您的叢集並存取Digital Advisor的所有功能。' 
---
= 在NetApp控制台中存取Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Digital Advisor現已與NetApp Console 完全整合。現在您可以從控制台使用者介面 (UI) 管理您的叢集並存取Digital Advisor的所有功能。

使用控制台，IT 專家和雲端架構師可以集中管理他們的混合多雲基礎架構。您只需要一個NetApp支援網站 (NSS) 帳戶即可存取控制台中的Digital Advisor 。



[[netapp-console]]
== NetApp控制台

可透過NetApp控制台存取Digital Advisor 。

NetApp控制台提供企業級跨本機和雲端環境的NetApp儲存和資料服務的集中管理。需要控制台才能存取和使用NetApp資料服務。作為管理介面，它使您能夠從一個介面管理許多儲存資源。控制台管理員可以控制企業內所有系統的儲存和服務的存取。

您無需授權或訂閱即可開始使用 NetApp Console，只有當您需要在雲端部署 Console 代理程式以確保與儲存系統或 NetApp 資料服務的連線時才會產生費用。但是，某些可從 Console 存取的 NetApp 資料服務需要授權或訂閱。

深入瞭解 https://docs.netapp.com/us-en/console-setup-admin/concept-overview.html["NetApp控制台"]。

您可以從控制台存取Digital Advisor來管理您的叢集。

.步驟
. 開啟 Web 瀏覽器並前往link:https://console.netapp.com/["安慰"^]。
. 選取* NetApp 支援網站 以您的「身份證明」登入*、然後輸入您的認證資料。
+
如果您之前已使用電子郵件和密碼建立了 Console 登入帳戶，則需要繼續使用該登入選項。

. 出現提示時、請使用NetApp 支援網站 您的功能驗證登入。
+
這次登入與步驟 2 中完成的登入不同。在步驟 2 中，您登入的是 Console。現在您正在登入 Digital Advisor。



* 結果 *

您現有的所有監視清單和組態都會顯示出來、現在您可以像平常一樣使用數位顧問。
