---
sidebar: sidebar 
permalink: reference_limitations_activeiq.html 
keywords: limitation, issues, not supported, drawbacks 
summary: 提供版本限制的相關資訊。 
---
= 已知限制
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
已知限制指出本產品版本不支援的平台、裝置或功能、或是無法與產品正確互通的平台、裝置或功能。請仔細檢閱這些限制。

存在下列限制：

* 僅適用於以7-Mode運作的支援系統（以7-Mode運作的VMware儲存系統即將終止支援壽命）Data ONTAP Data ONTAP
+
** 效能圖表
** 儲存效率


* 升級顧問不支援ONTAP 9.0之前的叢集式功能升級計畫。




== 編輯報價表可能需要60分鐘的時間、才能在數位顧問中反映出來

編輯觀察清單並不會立即更新數位顧問中的資訊。變更可能需要60分鐘才能反映在數位顧問中。



== 排程報告時會顯示空白報告

排定的報告只能搭配SupportEdge Advisor 支援服務SupportEdge Expert 合約使用。如果您的系統不符合SupportEdge Advisor 不完整支援SupportEdge Expert 合約或不完整支援合約、您可能會在排程報告時收到空白報告。



== 數位顧問可能需要60分鐘的時間來反映已確認和未確認的風險

數位顧問不會立即反映已確認和未確認的風險狀態。變更可能需要60分鐘的時間、才能反映在數位顧問和健康報告中。



== AutoSupport Widget 不適用於叢集和序號

AutoSupport Widget 不會針對叢集和序號搜尋提供警示。



== AutoSupport Widget 無法向下切入至序列層級 AutoSupport 詳細資料

在「 AutoSupport 報告」頁面上，按一下任何狀態，最近停止傳送的系統，或關閉 AutoSupport 的系統，都不會瀏覽至「健全狀況檢查」畫面。



== 「庫存」 Widget 中無法使用篩選和排序

您無法篩選和排序庫存 Widget 中的資料。如果您在「篩選條件」下拉式清單中選取 ONTAP AFF ， ONTAP ASA ， ONTAP Edge 或 ONTAP Select ，則不會顯示任何資料。
