---
sidebar: sidebar 
permalink: reference_new_activeiq.html 
keywords: 'what"s new, features, new' 
summary: 提供版本新功能的相關資訊。 
---
= 更新功能Active IQ
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
NetApp Active IQ We Digital Advisor提供下列功能與增強功能：



== 2022年5月12日



=== StorageGRID

其他容量指標會包含在StorageGRID 「能力與容量報告」中。



=== ClusterViewer

叢集的SnapMirror（資料保護）摘要現已包含在ClusterViewer中。



=== 升級工作流程

您現在可以使用升級工作流程來檢視升級建議、以及目標E系列版本中可用的新功能摘要。



=== 健康

* Ansible教戰手冊已經過強化、可降低軟體組態風險。
* 篩選條件已整合至健全狀況行動與風險中。




== 2022年4月7日



=== 健康

* 針對最新作業系統版本和「6個月」支援合約與支援結束KPI的關鍵建議評分已降低、以符合解決的減少急迫性。
* 遠端管理和HA配對（建議組態）的主要建議已更新、以納入NetApp支援網站的URL、以供客戶自助服務使用。




== 2022年3月31日



=== StorageGRID

您可以在網格檢視器中檢視租戶和鏟斗的相關資訊。



== 2022年3月24日



=== 健全狀況檢查儀表板

* 健全狀況評估執行摘要PPT的增強功能與錯誤修正。
* 能夠產生最低建議版本升級計畫。
* 健全狀況檢查區塊的增強功能、可識別每個KPI需要注意的節點數量。




=== StorageGRID

您可以在網格檢視器中檢視網格組態詳細資料。



=== Cloud Manager

Cloud Manager使用者現在可以在Active IQ 新的索引標籤中開啟鏈結（如適用）、類似Active IQ 於《》中的現有功能。



== 2022年1月12日



=== 設定飄移

* 您可以複製範本以複製原始範本。
* 您可以透過唯讀或完整存取這些範本的權限、與其他獲授權的使用者共用黃金範本。link:task_manage_template.html["瞭解方法"]。




== 2021年12月15日



=== 報告

* *叢集檢視器報告*：此報告提供客戶與報價表層級的單一叢集或多個叢集相關資訊。您可以使用ClusterViewer報告、將所有資訊下載到單一檔案中。您只能針對最多100個節點的觀察清單產生此報告。
* *效能報告*：此報告以單一壓縮檔提供叢集、節點、本機層級（Aggregate）和磁碟區效能的詳細資訊。每個壓縮檔都包含單一叢集的效能資料、有助於使用者分析每個叢集的資料。您只能針對最多100個節點的觀察清單產生此報告。




=== 與E系列系統整合

您可以在Active IQ VMware View中檢視所選E系列系統的容量詳細資料和效能圖表。



== 2021年11月18日



=== 儲存效率

您可以檢視由NetApp Cloud Insights 資源中心維護及監控之節點的儲存效率詳細資料。



== 2021年11月11日



=== 健全狀況檢查儀表板

* 新增的圖示位於「Health Check（狀況檢查）」區塊、僅適用於裝有SupportEdge Advisor 支援功能的系統SupportEdge Expert 。我們已針對「建議的軟體-軟體貨幣和韌體貨幣」區段、「建議的組態」和「最佳實務做法」進行增強。
* 在Active IQ 「支援內部與外部（客戶與合作夥伴）」使用者的「支援機密資料」橫幅上、新增「支援內部與外部（客戶與合作夥伴）」畫面。




=== 健全狀況與升級小工具

在「Wellness Action History（健康行動記錄）」欄中新增E系列升級建議和風險觸發日期、以強化儀表板。



=== ClusterViewer

ClusterViewer堆疊視覺化模組已經過強化、可納入「放大/縮小及儲存映像」功能。



=== 儲存效率

您可以檢視由NetApp Cloud Insights 執行維護與監控之系統的儲存效率詳細資料。



== 2021年10月14日



=== 可Ansible Inventory

您現在可以在區域和站台層級產生.yml和.ini檔案格式的Ansible庫存檔案。 link:task_view_inventory_details.html["瞭解方法"]。



=== 非作用中資料報告（印尼盾）

在「功能性顧問」畫面中、您可以啟動非作用中的資料報告（IDR）來監控Aggregate並產生可執行的教戰手冊。FabricPool link:task_monitor_and_tier_inactive_data_with_FabricPool_Advisor.html["深入瞭解"]



=== 飄移時間軸報告

您可以比較AutoSupport 過去90天的資料不完整、並產生飄移時間軸報告。 link:task_generate_drift_timeline_report.html["瞭解方法"]。



=== 符合法規的系統切換

健全狀況檢查儀表板已透過「最小作業系統」和「最新作業系統」索引標籤的切換功能增強、因此您可以檢視符合建議和最新版本最低要求且不符合要求的系統。



=== 重要建議摘要

在「健全狀況檢查」儀表板上、您可以檢視前5大主要建議摘要。



=== 適用於NetApp Cloud Volumes ONTAP 的選項卡和E系列平台

健全狀況檢查儀表板已透過Cloud Volumes ONTAP 更新功能的支援功能、可讓您檢視這些平台的健全狀況檢查KPI和詳細資料。

此外ONTAP 、我們也新增了「支援」索引標籤、以及其他平台、這些平台現在已啟用。



=== 容量

您可以在Cloud Volumes ONTAP 《關於NetApp的功能細節Active IQ 、請參閱：



=== 報告

報告時程已延長至12個月。排程報告即將到期時、您也會收到通知。



== 2021年9月30日



=== 客戶合格版本

客戶合格版本可協助支援客戶經理（SAM）管理客戶安裝基礎的一部分、其中裝載了需要下列條件的應用程式：

* 較早且有時不受支援的ONTAP 版本的不支援
* 或客戶的安裝基礎已通過測試和認證、可使用特定作業系統版本。




=== 技術案例工作流程

在儀表板和向下切入畫面中、資料圖表和折線圖都有圖形增強功能。您也可以選擇在長條圖中檢視該資料。在折線圖視窗中、您可以檢視、選取及取消選取這兩個使用者介面中的「開啟」、「關閉」和「個案總數」圖表。



=== 效能圖表

除了CSV格式之外、您現在也可以下載PNG和JPG格式的效能圖表。



=== 超過12個月的終止支援（EOS）控制器

健全狀況檢查儀表板的索引標籤已增強、顯示EOS超過12個月的控制器。



== 2021年9月16日



=== 健康

* 勒索軟體防禦小工具現在是Wellness工作流程的一部分、而非獨立式小工具。
* 在Wellness Review電子郵件中、您會看到勒索軟體防禦的相關資訊、而非續約。




=== 容量

您可以在ONTAP 本文件中檢視有關NetApp SolidNetApp®Select系統的容量詳細資料Active IQ 。



=== ClusterViewer

您可以在ClusterViewer的「視覺化」索引標籤中檢視纜線故障和其他錯誤。



== 2021年9月6日



=== StorageGRID

* 檢視AutoSupport 功能：檢視AutoSupport 有關功能不全及基礎節點的資訊。StorageGRID
* 《產品介紹：檢視有關應用程式的詳細資料、例如節點類型、應用裝置機型、磁碟機大小、磁碟機類型、RAID模式、StorageGRID StorageGRID 網格檢視器-網格資源清冊區段中的其他項目。
* 續約：檢視應續約的網格清單和基礎節點。
* E系列SANtricity 產品不含風險：在SANtricity Grid Dashboard - Wellness區段中檢視基礎節點的E系列產品不含風險。




=== 容量預測

容量預測小工具已更新為改良的演算法、可更妥善地因應系統重新組態。 link:reference_aiq_faq.html#capacity["深入瞭解"]。



== 2021年8月26日



=== 《數位顧問行動應用程式》Active IQ

您現在可以在Active IQ 「支援生物特徵辨識」行動應用程式上啟用生物特徵驗證。驗證可用的選項會因手機支援的功能而有所不同。

下載應用程式以深入瞭解：link:https://play.google.com/store/apps/details?id=com.netapp.aiqda&hl=en_IN&gl=US["支援數位顧問行動應用程式（Android）Active IQ"]
link:https://apps.apple.com/in/app/active-iq-digital-advisor/id1562880322["《數位顧問行動應用程式》（iOS）Active IQ"]



=== 健康

健全狀況小工具已透過勒索軟體的「防衛」屬性增強。您現在可以檢視勒索軟體偵測、預防及恢復的相關風險和修正行動。



== 2021年8月16日



=== 健康審查

您現在可以產生隨需報告。此外、您也可以從Wellness Review訂閱畫面下載上次排程的報告。



=== 庫存

在Grid Inventory（網格清單）選項卡中、您現在可以根據站台層級、以可擴充且可摺疊的格式來檢視節點詳細資料。



=== 混合模式叢集旗標

如果叢集有混合式硬體模型、則在叢集上套用的OS版本是所有節點都能使用的版本。因此、較新硬體機型的某些節點作業系統版本可能會從應該的位置縮減。為了讓這些混合模型叢集更為可見、我們已套用「混合模式」圖示。



=== 建議的組態/儲存虛擬機器（SVM）健全狀況：Volume層級摘要

按一下SVM表格中的藍色「Volume Summary」（Volume摘要）方塊後、會出現「快顯」視窗、顯示有關主控或附加至特定序號或實體節點之磁碟區的詳細資訊。



== 2021年7月12日



=== 系統韌體

您現在可以檢視系統韌體的相關資訊、這些資訊會隨ONTAP 附於主要版本和修補程式版本的資訊。您可以從「快速連結」功能表存取此功能。



=== 健全狀況檢查儀表板

* 健全狀況檢查儀表板已經過強化、加入藍色橫幅、通知使用者SupportEdge Advisor 在SupportEdge Expert 計算健全狀況分數時、不會將不受支援的系統納入考量。
* 建議的組態Widget已經過強化、可針對儲存VM（SVM）的失敗檢查提供深入分析、並可針對每個風險採取建議的修正行動。
* 對於ONTAP 使用不同硬體機型設定的叢集中的所有節點、建議的目標版本現在都相同。所有節點均支援目標版本。
* 您現在可以透過購買PVR來延長控制器、磁碟和磁碟櫃的EOS時程。購買時可在支援結束小工具中檢視PVR日期和延長詳細資料。PVR詳細資料也會在EOSL報告中提供。




=== 庫存

您可以在詳細目錄頁面上檢視硬體、軟體及不可回收磁碟的支援合約終止日期。



=== 支援服務升級

* 使用者介面已經過強化、可顯示Active IQ 您在支援中訂閱的特定支援服務項目。
* 您現在可以從系統儀表板提出升級支援服務訂閱的申請、以存取更多功能。 link:task_upgrade_support_offering.html["瞭解方法"]。




== 2021年6月25日



=== 彈性訂閱小工具

* 如果您已選擇ONTAP 使用「資源收集器」取得容量使用量的資料、您可以在「共用和磁碟」索引標籤中檢視檔案共用和磁碟的詳細資料。您可以識別即將提交容量的儲存空間、以節省儲存空間。
* Keystone -容量使用率儀表板上顯示並用於計費的容量使用量、現在是根據邏輯容量來決定。




== 2021年6月17日



=== 報告

您現在可以針對儲存VM中的所有Volume、針對任何日期、週或月產生彙總Volume效能報告。



=== 健康審查電子郵件

健康審查電子郵件已增強功能、可納入健康檢查和升級行動所提供的支援和授權資訊。



=== 升級工作流程

* 使用者介面已經過增強、可提供資訊的表格檢視。
* 您現在可以在ONTAP 「Upgrade Details」（升級詳細資料）畫面中、檢視有關停止支援的資訊。




=== 設定飄移

* Config Drivft現在支援200多AutoSupport 個功能區段、可建立黃金範本、並在客戶、站台、群組、觀察清單、叢集、 和主機。
* 組態飄移可讓您使用組態飄移報告有效負載中所含的Ansible教戰手冊來降低差異。




=== 健全狀況檢查儀表板

此功能已經過強化、可比較您的儲存VM（SVM）與預先定義的風險目錄、以評估落差並建議相關的修正行動。



== 2021年6月9日



=== 健全狀況檢查儀表板

您現在可以檢視根據其計算健全狀況分數的系統數量。此增強功能適用於「狀況檢查儀表板」中的所有屬性。



== 2021年5月20日



=== 針對容量新增要求使用「飄移聊天室」

如需容量新增要求的即時協助、請直接從儀表板與銷售人員交談。 link:task_identify_capacity_system.html["瞭解方法"]。



== 2021年4月29日

* 以下說明如何保護您的系統免受駭客和勒索軟體攻擊。 link:task_increase_protection_against_hackers_and_Ransomware_attacks.html["瞭解方法"]。
* 您可以避免停機和可能的資料遺失。 link:task_avoid_the_downtime_and_possible_data_loss.html["瞭解方法"]。
* 瞭解如何避免容量滿溢、以避免中斷運作。 link:task_avoid_a_volume_filling_up_to_prevent_an_outage.html["瞭解方法"]。




== 2021年4月7日



=== 觀察名單

第一次存取Active IQ 時、您應該先建立觀察清單、而非儀表板。您也可以檢視不同觀察名單的儀表板、編輯現有觀察名單的詳細資料、以及刪除觀察名單。



== 2021年2月24日



=== 設定飄移

此版本提供下列功能：

* 可在建立範本期間編輯屬性。
* 將各個部分分組AutoSupport 。
* 在客戶、站台、群組、觀察清單、叢集、 和主機名稱。 link:task_compare_config_drift_template.html["瞭解方法"]。




=== 報告

您可以產生或排程容量與效率報告、以檢視系統容量與儲存效率節約效益的詳細資訊。



== 2021年2月10日



=== StorageGRID

使用NextGen API架構啟用「支援資訊儀表板」StorageGRID 。

您可以使用StorageGRID 「報價單」儀表板來檢視報價表、客戶、群組和站台層級的資訊。

此版本提供下列功能：

* *詳細目錄小工具：*檢視StorageGRID 所選層級下可用的各種系統資源清冊。
* *健全狀況小工具：*根據StorageGRID 現有的可用系統ARS規則、檢視所有風險與行動、包括與之相關的風險與行動。
* *規劃小工具：*
+
** *新增容量：*若網格站台超過現有容量70%的臨界值、您將會收到通知。如果容量臨界值可能超過70%、您可以在未來1、3和6個月內、為站台的StorageGRID新增容量。
** *續約：* StorageGRID 若授權合約已到期或即將在未來6個月內到期、您將會收到通知。您可以選取一或多個系統、向NetApp支援團隊提出續約申請。


* *網格儀表板：*網格儀表板提供所選網格的健全狀況、規劃及組態詳細資料。
* *組態小工具：*提供StorageGRID 小工具中所選功能的基本詳細資料、例如網格名稱、主機名稱、序號、型號、作業系統版本、 客戶名稱、出貨地點及聯絡詳細資料。
* *網格檢視器：*在*組態*小工具中、您可以按一下*網格檢視器*連結來檢視網格組態的詳細資料。在*組態*小工具中、StorageGRID 按一下*網格檢視器*畫面中的*下載*按鈕、即可下載所選的「站台詳細資料」和「容量詳細資料」。
* *站台詳細資料：*此索引標籤提供每個站台可用的網格摘要和儲存節點。
* *網格摘要：*包含基本資訊、例如授權類型、授權容量、已安裝節點數量、支援期限（授權合約終止日期）、主要管理節點和主要管理節點的主要站台。此索引標籤也會提供站台名稱、以及在對應站台下標記的儲存節點數量。在此版本中、按一下可檢視對應站台儲存節點的超連結、即可檢視節點名稱清單。
* *容量詳細資料索引標籤：*提供為網格設定的網格層級和網站容量詳細資料。容量詳細資料、例如已安裝的儲存容量、可用儲存容量、已用儲存容量總計、以及用於資料和中繼資料的容量。網格和站台層級均提供這些詳細資料。




=== 資訊顧問FabricPool

「階層資料」按鈕已新增至FabricPool 「階層資料」儀表板、可讓您使用NetApp Cloud Manager將資料分層至低成本的物件儲存層。



=== 雲端就緒工作負載

您可以檢視儲存系統內可用的不同工作負載類型、並識別雲端就緒的工作負載。



== 2020年12月21日



=== 健全狀況檢查儀表板

儀表板已新增下列小工具：

* 建議軟體：此小工具提供所有軟體和韌體升級的合併清單、以及建議的貨幣。
* 訊號遺失：此小工具提供有關系統的分數和資訊、AutoSupport 這些系統因為某些原因而停止傳送某些資訊。如果AutoSupport 在7天內未從主機名稱接收到任何非功能性資料、則會提供相關資訊。




== 2020年11月12日



=== 使用API整合資料

您可以使用Active IQ NetApp API來提取感興趣的資料、並將其直接整合到貴公司的工作流程中。 link:concept_overview_API_service.html["深入瞭解"]。



=== 健全狀況-升級小工具

增強的Risk Advisor和Upgrade Advisor索引標籤可讓您檢視所有系統風險、並協助您規劃升級以降低所有風險。



=== 健全狀況檢查儀表板

建議的組態Widget已新增至儀表板、並提供遠端管理風險、備援磁碟機和故障磁碟機風險以及HA配對風險所監控的系統數量摘要。



=== 資訊顧問FabricPool

您可以監控叢集、將其分為四類：非作用中的本機層（Aggregate）資料、非作用中磁碟區資料、階層式資料、以及未啟用印尼盾的資料、藉此減少儲存佔用空間及相關成本。



=== 簡體中文和日文的本地化

現在提供中文、英文和日文三種語言的「世界資訊顧問」Active IQ 。



=== 報告

您可以產生或排程ClusterViewer報告、以檢視系統實體和邏輯組態的詳細資訊。 link:task_generate_reports.html["瞭解方法"]。



== 2020年10月15日



=== 健全狀況檢查儀表板

《支援不健全狀況檢查儀表板》Active IQ 提供整體環境的時間點審查。根據健全狀況檢查分數、您可以將儲存系統調整為建議的NetApp最佳實務做法、以利進行長期規劃、並改善安裝基礎的健全狀況。 link:concept_understand_health_check_assessment_dashboard.html["深入瞭解"]。



=== 設定飄移

此功能可讓您近乎即時地比較系統與叢集組態、以及偵測組態差異。 link:task_add_config_drift_template.html["瞭解如何新增組態偏移範本"]。



=== AutoSupport

您可以檢視AutoSupport 您的資料、並檢閱詳細資料。



=== 健康審查訂閱

您可以訂閱每月收到一封電子郵件通知、摘要說明系統的健全狀態、這些系統即將續約、且需要升級您安裝基礎上的NetApp產品。 link:task_subscribe_to_wellness_review_email.html["立即訂閱"]。



=== 報告

您可以使用報告功能立即產生報告、或排程每週或每月產生報告。 link:task_generate_reports.html["瞭解方法"]。



=== 手動AutoSupport 上傳

手動AutoSupport 上傳功能已增強、可改善使用者體驗。已提供額外的欄位、以供註解上傳狀態。



=== 彈性訂閱小工具

您可以監控NetApp Keystone 您的《支援、耗用及突發儲存容量、以利執行您的《支援NetApp訂閱服務（NetApp訂購服務）」。



== 2020年9月30日



=== 使用Ansible教戰手冊的韌體更新AFF FAS

文件內容已經過強化、包括有關下載、安裝及執行AFF 更新版的資訊、包括可FAS 執行的更新版的更新版、包括更新版的更新版、以及更新版的更新版。

link:task_update_AFF_FAS_firmware.html["瞭解如何AFF 使用「可執行教戰手冊」來更新BIOS和FAS BIOS韌體"]。



== 2020年8月18日



=== 效能

效能圖表已增強、可讓您評估磁碟區的效能。您可以在同一個畫面上的節點索引標籤、叢集索引標籤、本機層索引標籤和Volume索引標籤之間瀏覽及切換。 link:task_view_performance_graphs.html["瞭解方法"]。



=== 使用Ansible教戰手冊的韌體更新AFF FAS

功能強化的「更新版」和「更新版」韌體畫面、提供更好的使用者體驗。AFF FAS



== 2020年7月17日



=== 效能

效能圖表已增強、可讓您評估本機層級的效能。您可以在同一個畫面上的節點索引標籤、叢集索引標籤和本機層索引標籤之間瀏覽及切換。



=== 健康

健全狀況屬性已增強、可檢視所有受影響的系統、而不需深入瞭解行動和風險。



== 2020年6月19日



=== 產生庫存報告

您現在可以產生所選觀察名單的報告、並以電子郵件將報告傳送給最多5位收件者。 link:task_view_inventory_details.html["瞭解方法"]。



=== 效能

效能圖表已增強、可讓您評估儲存系統的叢集效能。您可以在同一個畫面上的節點索引標籤和叢集索引標籤之間瀏覽及切換。



=== 儲存效率

儲存效率小工具已經過增強、可讓您檢視叢集層級的儲存效率比與節約效益。您可以在同一個畫面上的節點索引標籤和叢集索引標籤之間瀏覽及切換。



=== 更新預設首頁

您現在可以提供您的意見反應、並告訴我們您更新Active IQ 預設首頁畫面的原因。



=== 更新至庫存小工具

庫存小工具已經過強化、可提供使用者友好的日期格式、用於平台結束支援的其他欄位、以及版本結束支援、藉此改善使用者體驗。



== 2020年5月19日



=== 設定預設首頁

您現在可以設定Active IQ 預設的主頁畫面以供使用。您可以將其設為Active IQ 「不知道數位顧問」或Active IQ 「不知道經典」。



=== 儲存效率

您可以檢視儲存系統的儲存效率比與節約效益、無論是否使用AFF Snapshot備份、以供支援各種系統、非AFF系統或兩者。您可以在節點層級檢視儲存效率資訊。 link:task_analyze_storage_efficiency.html["瞭解方法"]。



=== 效能

效能圖表可讓您評估儲存設備在不同重要領域的效能。



=== 使用Ansible教戰手冊進行韌體升級AFF FAS

使用AFF 儲存系統上的Ansible更新功能的更新功能、FAS 以減輕已識別的風險、並讓儲存系統保持最新狀態。



=== 停用健全狀況分數功能

目前正在暫時停用「健康評分」功能、以改善評分演算法並簡化整體體驗。



== 2020年4月2日



=== 就職總覽影片

入門影片可協助使用者快速熟悉Active IQ 《e數位顧問》的選項與功能。



=== 健全狀況分數

健全度分數可根據高風險數量和過期合約、為客戶提供已安裝基礎的整合分數。分數可以是「好」、「一般」或「差」。



=== 風險摘要

風險摘要提供有關風險、風險影響、修正行動的詳細資訊。



=== 支援確認及忽略風險

如果您確實想要減輕風險或無法減輕風險、請提供確認風險的選項。



== 2020年3月19日



=== 升級工作流程

您可以使用升級工作流程來檢視升級建議、以及目標ONTAP 版本可用的新功能摘要。 link:task_view_upgrade.html["瞭解方法"]。



=== 寶貴見解

您可以檢視Active IQ 透過NetApp及支援合約獲得的福利摘要。對於選定的系統、價值報告整合了過去一年的效益。 link:task_view_valuable_insight_widget.html["立即檢視"]。



=== 深入探討細節

提供更深入的資訊、這是深入瞭解資料、並根據需要立即深入瞭解彙總資訊的組成。



=== 增加容量

您可以主動識別已超過容量或接近90%容量的系統、並傳送要求以增加容量。



== 2020年2月29日



=== 增強的使用者介面

最新Active IQ 版的《數位顧問儀表板》提供個人化體驗。它能在不同的儀表板、小工具和螢幕上順暢無礙地導覽、並具備直覺功能。提供一體化體驗。它傳達比較、關係和趨勢。它提供深入見解、可協助您根據不同儀表板顯示的資料、偵測並驗證重要關係和有意義的差異。



=== 可自訂的儀表板

在一個或多個頁面或畫面上提供有關資料的重要見解和分析、協助您一目瞭然地監控系統。您也可以建立最多10個儀表板、並做出有效的業務決策。

link:concept_overview_dashboard.html["深入瞭解"]。



=== 利用本解決方法降低風險Active IQ Unified Manager

您可以檢視風險、並使用Active IQ Unified Manager 無法判斷的功能加以修正。 link:task_view_risks_remediated_unified_manager.html["瞭解方法"]。



=== 健康

提供儲存系統狀態的詳細資訊、這些資訊可分為下列6個小工具：

* 效能與效率
* 可用度與保護
* 容量
* 組態
* 安全性
* 續約


請參閱 link:concept_overview_wellness.html["分析健全屬性"] 以取得更多詳細資料。



=== 更聰明、更快速的搜尋

可讓您搜尋參數、例如序號、系統ID、主機名稱、站台名稱、群組名稱、 以及使用單一系統檢視的叢集名稱。您也可以搜尋系統群組、此外、您也可以依客戶名稱、站台名稱或依系統群組的群組名稱進行搜尋。
