---
sidebar: sidebar 
permalink: task_analyze_storage_efficiency.html 
keywords: capacity, storage efficiency, data reduction, savings 
summary: 檢視儲存系統的容量詳細資料和儲存效率節省。 
---
= 在Digital Advisor中查看容量和儲存效率節省情況
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以檢視系統的容量詳細資料及儲存效率節約效益、並採取適當行動。容量與儲存效率資訊可在叢集層級或節點層級檢視。


NOTE: E系列系統不支援此功能。

容量儀表板顯示系統的容量詳情和容量預測。容量預測利用歷史容量資訊來確定每個系統的使用率。根據已使用和已分配容量的歷史資料（如有，則為一年的資料），演算法會考慮每個系統的當前使用率，並產生未來 1 至 6 個月的系統使用率預測。

儲存效率儀表板會顯示資料減量比率、已使用的邏輯空間、已使用的實體空間，以及節省的總資料量。針對 AFF 系統、非 AFF 系統或兩者，不論是否包含 Snapshot 複本，都可以檢視其資料減量比率與節省量。您可以依據各項效率功能（例如 Volume 重複資料刪除、Volume 壓縮、資料精簡、FlexClone® Volume 及 Snapshot 複本），檢視客戶儲存設備所節省的總資料量。您可以檢視效率比率最佳的前 5 個儲存系統。您也可以在節點層級檢視 ONTAP 系統（包括 AFF A-Series、AFF C190、All SAN Array 及 FAS500）不含 Snapshot 複本的 SAN 與 NAS 效率。

video::8Ge3_0qlyxA[youtube,width=848,height=480]
.步驟
. 在左窗格中、按一下*容量與效率*。
+
預設會選取*容量*索引標籤。

. 在叢集和節點層級檢視容量詳細資料。
+
.. 檢視節點層級的容量預測。
+
對於部分系統、有關原始容量的資訊可在ClusterViewer中取得。ONTAP

.. 按一下*新增容量*、將通知傳送給NetApp或您的合作夥伴以新增容量。


. 檢視儲存系統的儲存效率和資料節約效益。
+
.. 如果您的儲存系統儲存效率比高於平均儲存效率比率、請按一下*分享您的成功案例*、讓我們瞭解所遵循的最佳實務做法。
.. 如果您的儲存系統儲存效率比低於平均儲存效率比率、請按一下*聯絡我們*、讓我們知道您的儲存系統組態。




如需容量與儲存效率的詳細資訊、請參閱 link:reference_aiq_faq.html["數位顧問的常見問題集"]。
